[package]
name = "crate-registry-github-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
poem = "3.0"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3.18"
octocrab = "0.39.0"
serde = "*"
serde_json = "*"
sha256 = "1.5"
